### ISSUE TITLE
Verify that cross-platform support works.

### ISSUE THREAD

**Issue by ajmwagar** [ajmwagar/bliss#3]
Need to verify that Windows & macOS builds are working. 

They should be since all the dependencies are cross-platform as well.

Will confirm.

**Comment by klemola** [comment]
Works on macOs Mojave on stable Rust (1.34.1)

```
 /tmp  bliss list                                                                                                                                                                      (2m 29s 869ms)
Supported Languages:
========================
1c, 1c-bitrix, a-frame, actionscript, ada, adobe, advancedinstaller, agda, al, alteraquartusii, altium, android, androidstudio, angular, anjuta, ansible, apachecordova, apachehadoop, appbuilder, appceleratortitanium, appcode, appcode+all, appcode+iml, appengine, aptanastudio, arcanist, archive, archives, archlinuxpackages, aspnetcore, assembler, ate, atmelstudio, ats, audio, automationstudio, autotools, autotools+strict, backup, ballerina, basercms, basic, batch, bazaar, bazel, bitrise, bitrix, bittorrent, blackbox, bloop, bluej, bookdown, bower, bricxcc, buck, c, c++, cake, cakephp, cakephp2, cakephp3, calabash, carthage, ceylon, cfwheels, chefcookbook, chocolatey, clean, clion, clion+all, clion+iml, clojure, cloud9, cmake, cocoapods, cocos2dx, cocoscreator, code, code-java, codeblocks, codecomposerstudio, codeigniter, codeio, codekit, codesniffer, coffeescript, commonlisp, composer, compressed, compressedarchive, compression, concrete5, coq, cordova, craftcms, crashlytics, crbasic, crossbar, crystal, csharp, cuda, cvs, d, dart, darteditor, data, database, datarecovery, dbeaver, delphi, diff, diskimage, django, dm, docfx, docpress, dotfilessh, dotsettings, dreamweaver, dropbox, drupal, drupal7, drupal8, eagle, easybook, eclipse, eiffelstudio, elasticbeanstalk, elisp, elixir, elm, emacs, ember, ensime, episerver, erlang, espresso, executable, exercism, expressionengine, extjs, fancy, fastlane, finale, firebase, flashbuilder, flask, flex, flexbuilder, floobits, flutter, font, fontforge, forcedotcom, forgegradle, fortran, freepascal, fsharp, fuelphp, fusetools, games, gcov, genero4gl, geth, ggts, gis, git, gitbook, go, godot, gpg, gradle, grails, greenfoot, grunt, gwt, haskell, hexo, hol, homeassistant, hsp, hugo, hyperledgercomposer, iar, iar_ewarm, iarembeddedworkbench, idapro, idris, igorpro, images, infer, inforcms, inforcrm, intellij, intellij+all, intellij+iml, ionic3, jabref, java, java-web, jboss, jboss-4-2-3-ga, jboss-6-x, jboss4, jboss6, jdeveloper, jekyll, jenv, jetbrains, jetbrains+all, jetbrains+iml, jgiven, jigsaw, jmeter, joe, joomla, jspm, julia, jupyternotebook, jupyternotebooks, justcode, kate, kdevelop4, keil, kentico, kicad, kirby2, kobalt, kohana, komodoedit, kotlin, labview, labviewnxg, lamp, laravel, latex, lazarus, leiningen, lemonstand, less, liberosoc, librarian-chef, libreoffice, lilypond, linux, lithium, logtalk, lua, lyx, m2e, macos, magento, magento1, magento2, magic-xpa, matlab, maven, mavensmate, mean, mercurial, mercury, metals, metaprogrammingsystem, meteor, meteorjs, microsoftoffice, mikroc, moban, modelsim, modx, momentics, monodevelop, mplabx, mule, nanoc, nativescript, ncrunch, nesc, netbeans, nette, nikola, nim, ninja, node, notepadpp, nuxt, nuxtjs, nwjs, objective-c, ocaml, octave, octobercms, opa, opencart, opencv, openfoam, openframeworks, openframeworks+visualstudio, oracleforms, osx, otto, packer, particle, patch, pawn, perl, perl6, ph7cms, phalcon, phoenix, phpcodesniffer, phpstorm, phpstorm+all, phpstorm+iml, pimcore, pimcore4, pimcore5, pinegrow, platformio, playframework, plone, polymer, powershell, premake-gmake, prepros, prestashop, processing, progressabl, psoccreator, puppet, puppet-librarian, purebasic, purescript, putty, pvs, pycharm, pycharm+all, pycharm+iml, pydev, python, qml, qooxdoo, qt, qtcreator, r, racket, rails, reactnative, red, redcar, redis, rhodesrhomobile, rider, root, ros, ruby, rubymine, rubymine+all, rubymine+iml, rust, salesforce, salesforcedx, sas, sass, sbt, scala, scheme, scons, scrivener, sdcc, seamgen, senchatouch, serverless, shopware, silverstripe, sketchup, slickedit, smalltalk, snap, snapcraft, solidity, soliditytruffle, sonar, sonarqube, sourcepawn, splunk, spreadsheet, standardml, stata, stdlib, stella, stellar, stylus, sublimetext, sugarcrm, svn, swift, swiftpackagemanager, swiftpm, symfony, symphonycms, synology, synopsysvcs, tags, tarmainstallmate, terraform, test, testcomplete, testinfra, tex, text, textmate, textpattern, theos-tweak, thinkphp, tortoisegit, tower, turbogears2, twincat, typings, typo3, typo3-composer, umbraco, unity, unrealengine, vaadin, vagrant, valgrind, vapor, venv, vertx, video, vim, virtualenv, virtuoso, visualstudio, visualstudiocode, vivado, vlab, vuejs, vvvv, waf, wakanda, web, webmethods, webstorm, webstorm+all, webstorm+iml, werckercli, windows, wintersmith, wordpress, wyam, xamarinstudio, xcode, xcodeinjection, xilinx, xilinxise, xilinxvivado, xill, xojo, xtext, y86, yeoman, yii, yii2, zendframework, zephir, zig, zukencr8000

 /tmp  bliss rust                                                                                                                                                                             (917ms)

# Created by https://www.gitignore.io/api/rust
# Edit at https://www.gitignore.io/?templates=rust

### Rust ###
# Generated by Cargo
# will have compiled files and executables
/target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk

# End of https://www.gitignore.io/api/rust
```

**Comment by astra-midnight** [comment]
I  got an error when trying to build with Rust 1.34.1 on Windows 10 (1903).

```
error[E0061]: this function takes 1 parameter but 0 parameters were supplied
  --> C:\Users\Chloe Stars\.cargo\registry\src\github.com-1ecc6299db9ec823\bliss-0.1.2\src\lib.rs:21:27
   |
21 |         let cache = match Cache::from() {
   |                           ^^^^^^^^^^^^^ expected 1 parameter

error[E0308]: mismatched types
  --> C:\Users\Chloe Stars\.cargo\registry\src\github.com-1ecc6299db9ec823\bliss-0.1.2\src\lib.rs:22:13
   |
21 |         let cache = match Cache::from() {
   |                           ------------- this match expression has type `Cache`
22 |             Ok(cache) => cache,
   |             ^^^^^^^^^ expected struct `Cache`, found enum `std::result::Result`
   |
   = note: expected type `Cache`
              found type `std::result::Result<_, _>`

error[E0308]: mismatched types
  --> C:\Users\Chloe Stars\.cargo\registry\src\github.com-1ecc6299db9ec823\bliss-0.1.2\src\lib.rs:23:13
   |
21 |         let cache = match Cache::from() {
   |                           ------------- this match expression has type `Cache`
22 |             Ok(cache) => cache,
23 |             Err(e) => {
   |             ^^^^^^ expected struct `Cache`, found enum `std::result::Result`
   |
   = note: expected type `Cache`
              found type `std::result::Result<_, _>`

error: aborting due to 3 previous errors

Some errors occurred: E0061, E0308.
For more information about an error, try `rustc --explain E0061`.
error: failed to compile `bliss v0.1.2`, intermediate artifacts can be found at `C:\Users\CHLOES~1\AppData\Local\Temp\cargo-install1TdyGQ`

Caused by:
  Could not compile `bliss`.

To learn more, run the command again with --verbose.
```

**Comment by ajmwagar** [comment]
Thank you. I will look into the Windows error.

**Comment by ajmwagar** [comment]
Should work on Windows now. It was using the default implementation of `Cache::from()` due to a misplaced `#[cfg(unix)]`.

**Comment by astra-midnight** [comment]
I ran cargo build bliss and and it now fails with 

```
  Compiling bliss v0.1.2                                                                    
error[E0061]: this function takes 1 parameter but 0 parameters were supplied                 
  --> C:\Users\Chloe Stars\.cargo\registry\src\github.com-1ecc6299db9ec823\bliss-0.1.2\src\li
b.rs:21:27                                                                                   
   |                                                                                         
21 |         let cache = match Cache::from() {                                               
   |                           ^^^^^^^^^^^^^ expected 1 parameter                            
                                                                                             
error[E0308]: mismatched types                                                               
  --> C:\Users\Chloe Stars\.cargo\registry\src\github.com-1ecc6299db9ec823\bliss-0.1.2\src\li
b.rs:22:13                                                                                   
   |                                                                                         
21 |         let cache = match Cache::from() {                                               
   |                           ------------- this match expression has type `Cache`          
22 |             Ok(cache) => cache,                                                         
   |             ^^^^^^^^^ expected struct `Cache`, found enum `std::result::Result`         
   |                                                                                         
   = note: expected type `Cache`                                                             
              found type `std::result::Result<_, _>`                                         
                                                                                             
error[E0308]: mismatched types                                                               
  --> C:\Users\Chloe Stars\.cargo\registry\src\github.com-1ecc6299db9ec823\bliss-0.1.2\src\li
b.rs:23:13                                                                                   
   |                                                                                         
21 |         let cache = match Cache::from() {                                               
   |                           ------------- this match expression has type `Cache`          
22 |             Ok(cache) => cache,                                                         
23 |             Err(e) => {                                                                 
   |             ^^^^^^ expected struct `Cache`, found enum `std::result::Result`            
   |                                                                                         
   = note: expected type `Cache`                                                             
              found type `std::result::Result<_, _>`                                         
                                                                                             
error: aborting due to 3 previous errors                                                     
                                                                                             
Some errors occurred: E0061, E0308.                                                          
For more information about an error, try `rustc --explain E0061`.                            
error: failed to compile `bliss v0.1.2`, intermediate artifacts can be found at `C:\Users\Chl
oe Stars\AppData\Local\Temp\cargo-installQqOXtC`                                             
                                                                                             
Caused by:                                                                                   
  Could not compile `bliss`.                                              
```

**Comment by ajmwagar** [comment]
Dang. I'll give it another shot when I'm back on a machine with Windows. Thanks for trying.

**Comment by dieseltravis** [comment]
I cloned from master and I think it built ok:
```
D:\projects\github\bliss [master ≡]> cargo build
  Downloaded tokio-timer v0.2.10                                                                                                                          
  Downloaded cfg-if v0.1.7 
  Downloaded cc v1.0.36 
  Downloaded synstructure v0.10.1 
  Downloaded backtrace v0.3.15 
  Downloaded tokio v0.1.19
   Compiling winapi v0.3.7 
   Compiling semver-parser v0.7.0
   Compiling autocfg v0.1.2
   Compiling winapi-build v0.1.1
   Compiling rand_core v0.4.0
   Compiling byteorder v1.3.1 
   Compiling version_check v0.1.5
   Compiling libc v0.2.54
   Compiling stable_deref_trait v1.1.1
   Compiling cfg-if v0.1.7
   Compiling winapi v0.2.8 
   Compiling proc-macro2 v0.4.30 
   Compiling arrayvec v0.4.10 
   Compiling unicode-xid v0.1.0 
   Compiling nodrop v0.1.13 
   Compiling smallvec v0.6.9 
   Compiling scopeguard v0.3.3 
   Compiling lazy_static v1.3.0
   Compiling slab v0.4.2
   Compiling syn v0.15.34 
   Compiling memchr v2.2.0 
   Compiling siphasher v0.2.3 
   Compiling futures v0.1.27 
   Compiling memoffset v0.2.1 
   Compiling fnv v1.0.6 
   Compiling lazycell v1.2.1
   Compiling build_const v0.2.1 
   Compiling matches v0.1.8
   Compiling ryu v0.2.8 
   Compiling rustc-demangle v0.1.14 
   Compiling itoa v0.4.4 
   Compiling regex v1.1.6
   Compiling httparse v1.3.3 
   Compiling cc v1.0.36 
   Compiling failure_derive v0.1.5 
   Compiling ucd-util v0.1.3
   Compiling serde v1.0.91 
   Compiling try-lock v0.2.2 
   Compiling adler32 v1.0.3 
   Compiling crc32fast v1.2.0 
   Compiling string v0.1.3 
   Compiling indexmap v1.0.2
   Compiling percent-encoding v1.0.1
   Compiling utf8-ranges v1.0.2 
   Compiling native-tls v0.2.3 
   Compiling encoding_rs v0.8.17
   Compiling dtoa v0.4.4 
   Compiling unicode-width v0.1.5 
   Compiling vec_map v0.8.1 
   Compiling bitflags v1.0.4 
   Compiling strsim v0.8.0 
   Compiling log v0.4.6 
   Compiling try_from v0.3.2 
   Compiling owning_ref v0.4.0 
   Compiling kernel32-sys v0.2.2 
   Compiling ws2_32-sys v0.2.1 
   Compiling rand_core v0.3.1
   Compiling unicase v1.4.2 
   Compiling error-chain v0.12.1
   Compiling unicase v2.4.0 
   Compiling rand_chacha v0.1.1 
   Compiling rand_pcg v0.1.2 
   Compiling rand v0.6.5 
   Compiling backtrace v0.3.15 
   Compiling semver v0.9.0
   Compiling crossbeam-utils v0.6.5
   Compiling thread_local v0.3.6
   Compiling tokio-trace-core v0.1.0
   Compiling unicode-bidi v0.3.4
   Compiling unicode-normalization v0.1.8 
   Compiling crc v1.8.1 
   Compiling miniz_oxide v0.2.1 
   Compiling regex-syntax v0.6.6 
   Compiling textwrap v0.11.0
   Compiling rand_isaac v0.1.1 
   Compiling rand_xorshift v0.1.1
   Compiling rand_hc v0.1.0 
   Compiling lock_api v0.1.5
   Compiling miniz_oxide_c_api v0.2.1 
   Compiling tokio-sync v0.1.5
   Compiling want v0.0.6 
   Compiling rustc_version v0.2.3 
   Compiling tokio-executor v0.1.7 
   Compiling crossbeam-queue v0.1.2 
   Compiling num_cpus v1.10.0 
   Compiling crossbeam-epoch v0.7.1 
   Compiling base64 v0.10.1
   Compiling aho-corasick v0.7.3 
   Compiling parking_lot_core v0.4.0 
   Compiling quote v0.6.12 
   Compiling tokio-current-thread v0.1.6 
   Compiling tokio-timer v0.2.10
   Compiling phf_shared v0.7.24 
   Compiling futures-cpupool v0.1.8 
   Compiling crossbeam-deque v0.7.1 
   Compiling mime v0.3.13 
   Compiling phf v0.7.24 
   Compiling idna v0.1.5 
   Compiling flate2 v1.0.7 
   Compiling url v1.7.2
   Compiling rand_jitter v0.1.4 
   Compiling rand_os v0.1.3 
   Compiling net2 v0.2.33 
   Compiling schannel v0.1.15
   Compiling time v0.1.42 
   Compiling atty v0.2.11 
   Compiling dirs v1.0.5 
   Compiling clap v2.33.0 
   Compiling cookie v0.11.1 
   Compiling publicsuffix v1.5.2 
   Compiling serde_json v1.0.39 
   Compiling serde_urlencoded v0.5.5
   Compiling synstructure v0.10.1 
   Compiling serde_derive v1.0.91
   Compiling phf_generator v0.7.24 
   Compiling tokio-threadpool v0.1.14
   Compiling uuid v0.7.4
   Compiling phf_codegen v0.7.24 
   Compiling mime_guess v2.0.0-alpha.6 
   Compiling parking_lot v0.7.1 
   Compiling failure v0.1.5
   Compiling cookie_store v0.5.1
   Compiling iovec v0.1.2 
   Compiling miow v0.2.1
   Compiling bytes v0.4.12
   Compiling tokio-io v0.1.12 
   Compiling http v0.1.17
   Compiling mio v0.6.16
   Compiling tokio-reactor v0.1.9
   Compiling tokio-tcp v0.1.3
   Compiling tokio v0.1.19
   Compiling h2 v0.1.18 
   Compiling hyper v0.12.28 
   Compiling hyper-tls v0.3.2 
   Compiling reqwest v0.9.16 
   Compiling bliss v0.1.1 (D:\projects\github\bliss) 
    Finished dev [unoptimized + debuginfo] target(s) in 1m 03s
```

It looks like that is v0.1.1 but when I run `cargo install bliss` it tries to install v.0.1.2 and fails with the same error as above.

rustc 1.34.2 (6c2484dc3 2019-05-13)
cargo 1.34.0 (6789d8a0a 2019-04-01)
Windows 10 1809 (10.0.17763.0 x64)

The compiled binary appears to work great though! 👍

**Comment by ajmwagar** [comment]
Awesome. It looks like I need to run `cargo publish` with the new version.
